[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ALWAYS"

[[services]]
name = "3x-ui"
type = "WEB"
plan = "starter"
numInstances = 1
ports = [{ port = 2053, handlers = ["HTTP"] }]

[variables]
XUI_ENABLE_FAIL2BAN = "false"

[[services.volumes]]
name = "x-ui-data"
mountPath = "/etc/x-ui"
